//! Domain layer — repository implementations backed by the `impl_repository!` macro.
//!
//! Each sub-module declares a repository struct (e.g. `UserRepository`) and any
//! custom query methods beyond the 13 generated by the macro.  Application and
//! service code depends on these repositories for all database access.

pub mod repositories;

pub use repositories::*;
