#[macro_export]
/// Implements a Diesel (async) repository with common CRUD + pagination helpers.
///
/// This macro generates:
/// - A repository struct: `pub struct $repo_name {}`
/// - A `new()` constructor
/// - CRUD helpers (`create`, `find_by_id`, `find_where`, `update`, `delete`, etc.)
/// - Counting + pagination helpers
///
/// # Parameters
/// - `$repo_name`: The repository type name to generate (e.g. `UsersRepository`)
/// - `$entity`: The entity/model type (e.g. `User`)
/// - `$table`: The Diesel schema table path (e.g. `crate::schema::users::table`)
/// - `$pk`: The primary key column path (e.g. `crate::schema::users::id`)
/// - `$pk_type`: The Rust type for the primary key (e.g. `uuid::Uuid`, `i32`, etc.)
///
/// # Example
/// ```rust
/// // Given a diesel entity
/// // impl_repository!(
/// //    UsersRepository for User,
/// //    crate::schema::users::table,
/// //    crate::schema::users::id,
/// //    Uuid
/// //);
///
/// // Usage:
/// // let repo = UsersRepository::new();
/// // let mut conn = db.get_conn().await?;
/// // let created = repo.create(&mut conn, &new_user).await?;
/// ```
macro_rules! impl_repository {
    ($repo_name:ident for $entity:ty, $table:path, $pk:path, $pk_type:ty) => {
        use $crate::DbConnection;

        /// Repository generated by [`impl_repository!`].
        ///
        /// # Example
        /// ```rust
        /// // let repo = UsersRepository::new();
        /// ```
        #[derive(Default)]
        pub struct $repo_name {}

        impl $repo_name {
            /// Creates a new repository instance.
            ///
            /// # Example
            /// ```rust
            /// // let repo = UsersRepository::new();
            /// ```
            pub fn new() -> Self {
                Self {}
            }

            // --------------------
            // CREATE
            // --------------------

            /// Inserts a single entity row and returns the inserted record.
            ///
            /// The entity must be `Insertable<$table>`.
            ///
            /// # Example
            /// ```rust
            /// // let repo = UsersRepository::new();
            /// // let created = repo.create(&mut conn, &new_user).await?;
            /// ```
            pub async fn create(
                &self,
                conn: &mut DbConnection<'_>,
                entity: &$entity,
            ) -> Result<$entity, diesel::result::Error>
            where
                $entity: diesel::Insertable<$table> + Send + Sync,
            {
                use diesel_async::RunQueryDsl;

                diesel::insert_into($table)
                    .values(entity)
                    .get_result(conn)
                    .await
            }

            /// Inserts multiple entity rows and returns all inserted records.
            ///
            /// # Example
            /// ```rust
            /// // let repo = UsersRepository::new();
            /// // let created = repo.create_many(&mut conn, &new_users).await?;
            /// ```
            pub async fn create_many(
                &self,
                conn: &mut DbConnection<'_>,
                entities: &[$entity],
            ) -> Result<Vec<$entity>, diesel::result::Error>
            where
                $entity: diesel::Insertable<$table> + Send + Sync,
            {
                use diesel_async::RunQueryDsl;

                diesel::insert_into($table)
                    .values(entities)
                    .get_results(conn)
                    .await
            }

            // --------------------
            // READ
            // --------------------

            /// Finds a single record by its primary key.
            ///
            /// Returns `Ok(None)` if no row is found.
            ///
            /// # Example
            /// ```rust
            /// // let repo = UsersRepository::new();
            /// // let user = repo.find_by_id(&mut conn, user_id).await?;
            /// // if let Some(u) = user { /* ... */ }
            /// ```
            pub async fn find_by_id(
                &self,
                conn: &mut DbConnection<'_>,
                id_value: $pk_type,
            ) -> Result<Option<$entity>, diesel::result::Error> {
                use diesel::ExpressionMethods;
                use diesel::OptionalExtension;
                use diesel_async::RunQueryDsl;

                let q = diesel::query_dsl::methods::FilterDsl::filter($table, $pk.eq(id_value));
                q.first(conn).await.optional()
            }

            /// Finds records matching the provided filter expression.
            ///
            /// The filter must be a Diesel boolean expression compatible with the table
            /// and must be non-aggregate.
            ///
            /// # Example
            /// ```rust
            /// // use diesel::prelude::*;
            /// // use crate::schema::users::dsl::*;
            /// //
            /// // let repo = UsersRepository::new();
            /// // let found = repo.find_where(&mut conn, email.eq("a@b.com")).await?;
            /// ```
            pub async fn find_where<'a, F>(
                &self,
                conn: &mut DbConnection<'a>,
                filter_expr: F,
            ) -> Result<Vec<$entity>, diesel::result::Error>
            where
                F: diesel::expression::BoxableExpression<
                        $table,
                        diesel::pg::Pg,
                        SqlType = diesel::sql_types::Bool,
                    > + diesel::expression::NonAggregate
                    + Send
                    + 'a,
            {
                use diesel::prelude::*;
                use diesel_async::RunQueryDsl;

                $table
                    .into_boxed::<diesel::pg::Pg>()
                    .filter(filter_expr)
                    .load::<$entity>(conn)
                    .await
            }

            // --------------------
            // UPDATE
            // --------------------

            /// Updates a single record by primary key using the provided changeset,
            /// returning the updated record.
            ///
            /// # Example
            /// ```rust
            /// // use crate::schema::users;
            /// //
            /// // #[derive(AsChangeset)]
            /// // #[diesel(table_name = users)]
            /// // struct UserChanges { email: String }
            /// //
            /// // let repo = UsersRepository::new();
            /// // let updated = repo
            /// //   .update(&mut conn, user_id, UserChanges { email: "new@x.com".into() })
            /// //   .await?;
            /// ```
            pub async fn update<'a, C>(
                &self,
                conn: &mut DbConnection<'a>,
                id_value: $pk_type,
                changes: C,
            ) -> Result<$entity, diesel::result::Error>
            where
                C: diesel::AsChangeset<Target = $table> + Send + 'a,
                <C as diesel::AsChangeset>::Changeset:
                    diesel::query_builder::QueryFragment<diesel::pg::Pg> + Send,
            {
                use diesel::prelude::*;
                use diesel_async::RunQueryDsl;

                diesel::update($table.filter($pk.eq(id_value)))
                    .set(changes)
                    .get_result::<$entity>(conn)
                    .await
            }

            /// Updates the first matching record for the given filter expression,
            /// returning the updated record.
            ///
            /// # Example
            /// ```rust
            /// // use diesel::prelude::*;
            /// // use crate::schema::users::dsl::*;
            /// //
            /// // #[derive(AsChangeset)]
            /// // #[diesel(table_name = crate::schema::users)]
            /// // struct UserChanges { email: String }
            /// //
            /// // let repo = UsersRepository::new();
            /// // let updated = repo
            /// //   .update_where(&mut conn, email.eq("old@x.com"), UserChanges { email: "new@x.com".into() })
            /// //   .await?;
            /// ```
            pub async fn update_where<'a, F, C>(
                &self,
                conn: &mut DbConnection<'a>,
                filter_expr: F,
                changes: C,
            ) -> Result<$entity, diesel::result::Error>
            where
                C: diesel::AsChangeset<Target = $table> + Send + 'a,
                <C as diesel::AsChangeset>::Changeset:
                    diesel::query_builder::QueryFragment<diesel::pg::Pg> + Send,
                F: diesel::expression::BoxableExpression<
                        $table,
                        diesel::pg::Pg,
                        SqlType = diesel::sql_types::Bool,
                    > + diesel::expression::NonAggregate
                    + Send
                    + 'a,
            {
                use diesel::prelude::*;
                use diesel_async::RunQueryDsl;

                diesel::update($table.filter(filter_expr))
                    .set(changes)
                    .get_result::<$entity>(conn)
                    .await
            }

            // --------------------
            // DELETE
            // --------------------

            /// Deletes a single record by primary key and returns the deleted record.
            ///
            /// # Example
            /// ```rust
            /// // let repo = UsersRepository::new();
            /// // let deleted = repo.delete(&mut conn, user_id).await?;
            /// ```
            pub async fn delete(
                &self,
                conn: &mut DbConnection<'_>,
                id_value: $pk_type,
            ) -> Result<$entity, diesel::result::Error> {
                use diesel::prelude::*;
                use diesel_async::RunQueryDsl;

                diesel::delete($table.filter($pk.eq(id_value)))
                    .get_result::<$entity>(conn)
                    .await
            }

            // --------------------
            // COUNT / EXISTS
            // --------------------

            /// Counts total rows in the table.
            ///
            /// # Example
            /// ```rust
            /// // let repo = UsersRepository::new();
            /// // let total = repo.count(&mut conn).await?;
            /// ```
            pub async fn count(
                &self,
                conn: &mut DbConnection<'_>,
            ) -> Result<i64, diesel::result::Error> {
                use diesel::prelude::*;
                use diesel_async::RunQueryDsl;

                $table.count().get_result(conn).await
            }

            // --------------------
            // PAGINATION
            // --------------------

            /// Fetches a page of records ordered by primary key descending, and returns
            /// `(results, total_count)`.
            ///
            /// Note: `page` is treated as 1-based in the offset formula `(page - 1) * per_page`.
            ///
            /// # Example
            /// ```rust
            /// // let repo = UsersRepository::new();
            /// // let (rows, total) = repo.paginate_all(&mut conn, 1, 20).await?;
            /// ```
            pub async fn paginate_all(
                &self,
                conn: &mut DbConnection<'_>,
                page: i64,
                per_page: i64,
            ) -> Result<(Vec<$entity>, i64), diesel::result::Error> {
                use diesel::prelude::*;
                use diesel::query_dsl::methods::OrderDsl;
                use diesel_async::RunQueryDsl;

                let results = OrderDsl::order($table, $pk.desc())
                    .limit(per_page)
                    .offset((page - 1) * per_page)
                    .load(conn)
                    .await?;

                let total = $table.count().get_result(conn).await?;
                Ok((results, total))
            }

            /// Fetches a filtered page of records and returns `(results, total_count)`.
            ///
            /// Uses a `make_filter` closure so the filter expression can be constructed twice
            /// (once for `count()` and once for `load()`).
            ///
            /// `page` and `per_page` are clamped to at least `1`.
            ///
            /// # Example
            /// ```rust
            /// // use diesel::prelude::*;
            /// // use crate::schema::users::dsl::*;
            /// //
            /// // let repo = UsersRepository::new();
            /// // let (rows, total) = repo
            /// //   .paginate_where(&mut conn, 1, 20, || email.like("%@gmail.com"))
            /// //   .await?;
            /// ```
            pub async fn paginate_where<'a, MakeF, F>(
                &self,
                conn: &mut DbConnection<'a>,
                page: i64,
                per_page: i64,
                make_filter: MakeF,
            ) -> Result<(Vec<$entity>, i64), diesel::result::Error>
            where
                MakeF: Fn() -> F + Send + Sync + 'a,
                F: diesel::expression::BoxableExpression<
                        $table,
                        diesel::pg::Pg,
                        SqlType = diesel::sql_types::Bool,
                    > + diesel::expression::NonAggregate
                    + Send
                    + 'a,
            {
                use diesel::prelude::*;
                use diesel::ExpressionMethods;
                use diesel_async::RunQueryDsl;

                let page = page.max(1);
                let per_page = per_page.max(1);
                let offset = (page - 1) * per_page;

                let total: i64 = $table
                    .into_boxed::<diesel::pg::Pg>()
                    .filter(make_filter())
                    .count()
                    .get_result(conn)
                    .await?;

                let results: Vec<$entity> = $table
                    .into_boxed::<diesel::pg::Pg>()
                    .filter(make_filter())
                    .order($pk.desc())
                    .limit(per_page)
                    .offset(offset)
                    .load::<$entity>(conn)
                    .await?;

                Ok((results, total))
            }
        }
    };
}
