// @generated by scripts/gen_db_models_and_enums.sh
// DO NOT EDIT MANUALLY

use chrono::{DateTime, Utc};
use diesel::prelude::*;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::schema_enums::*;

// ============================================================================
// Model: ApiToken
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::api_tokens)]
#[diesel(primary_key(api_token_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct ApiToken {
    pub api_token_id: Uuid,
    pub user_id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub token_hash: String,
    pub expires_at: Option<DateTime<Utc>>,
    pub last_used_at: Option<DateTime<Utc>>,
    pub revoked_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: Option<DateTime<Utc>>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

// ============================================================================
// Model: AuthConfig
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::auth_configs)]
#[diesel(primary_key(config_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct AuthConfig {
    pub config_id: Uuid,
    pub user_id: Uuid,
    pub key_hash: String,
    pub algorithm: String,
    pub issuer: String,
    pub default_expiry_seconds: i32,
    pub is_active: bool,
    pub rotated_at: Option<DateTime<Utc>>,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

// ============================================================================
// Model: EmailTemplate
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::email_templates)]
#[diesel(primary_key(template_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct EmailTemplate {
    pub template_id: Uuid,
    pub template_type: EmailTemplateType,
    pub subject: String,
    pub body_text: String,
    pub body_html: Option<String>,
    pub is_active: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: Option<DateTime<Utc>>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

// ============================================================================
// Model: EmailVerification
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::email_verifications)]
#[diesel(primary_key(verification_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct EmailVerification {
    pub verification_id: Uuid,
    pub identity_id: Uuid,
    pub token_hash: String,
    pub expires_at: DateTime<Utc>,
    pub verified_at: Option<DateTime<Utc>>,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

// ============================================================================
// Model: OidcAuthCode
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::oidc_auth_codes)]
#[diesel(primary_key(oidc_auth_code_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct OidcAuthCode {
    pub oidc_auth_code_id: Uuid,
    pub code_hash: String,
    pub oidc_client_id: Uuid,
    pub user_id: Uuid,
    pub redirect_uri: String,
    pub scope: String,
    pub nonce: Option<String>,
    pub code_challenge: String,
    pub code_challenge_method: String,
    pub expires_at: DateTime<Utc>,
    pub consumed_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

// ============================================================================
// Model: OidcClient
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::oidc_clients)]
#[diesel(primary_key(oidc_client_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct OidcClient {
    pub oidc_client_id: Uuid,
    pub tenant_id: Option<Uuid>,
    pub client_id: String,
    pub client_secret_hash: Option<String>,
    pub name: String,
    pub redirect_uris: Vec<String>,
    pub allowed_scopes: Vec<String>,
    pub pkce_required: bool,
    pub is_confidential: bool,
    pub created_at: DateTime<Utc>,
}

// ============================================================================
// Model: OidcSigningKey
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::oidc_signing_keys)]
#[diesel(primary_key(oidc_signing_key_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct OidcSigningKey {
    pub oidc_signing_key_id: Uuid,
    pub kid: String,
    pub alg: String,
    pub public_jwk_json: serde_json::Value,
    pub private_key_encrypted: Vec<u8>,
    pub status: String,
    pub created_at: DateTime<Utc>,
}

// ============================================================================
// Model: PasswordResetToken
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::password_reset_tokens)]
#[diesel(primary_key(reset_token_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct PasswordResetToken {
    pub reset_token_id: Uuid,
    pub identity_id: Uuid,
    pub token_hash: String,
    pub expires_at: DateTime<Utc>,
    pub used_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: Option<DateTime<Utc>>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

// ============================================================================
// Model: Policy
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::policies)]
#[diesel(primary_key(policy_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Policy {
    pub policy_id: Uuid,
    pub tenant_id: Option<Uuid>,
    pub environment: String,
    pub name: String,
    pub description: Option<String>,
    pub active_version: i64,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub is_active: bool,
}

// ============================================================================
// Model: PolicyVersion
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::policy_versions)]
#[diesel(primary_key(policy_version_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct PolicyVersion {
    pub policy_version_id: Uuid,
    pub policy_id: Uuid,
    pub version: i64,
    pub rules: serde_json::Value,
    pub rules_hash: String,
    pub compiled_rules: Vec<u8>,
    pub compiled_hash: String,
    pub compiler_version: String,
    pub compiled_at: DateTime<Utc>,
    pub created_at: DateTime<Utc>,
    pub is_active: bool,
}

// ============================================================================
// Model: ProviderConfiguration
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::provider_configurations)]
#[diesel(primary_key(configuration_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct ProviderConfiguration {
    pub configuration_id: Uuid,
    pub tenant_id: Option<Uuid>,
    pub provider: String,
    pub config_encrypted: Vec<u8>,
    pub config_redacted: serde_json::Value,
    pub is_active: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

// ============================================================================
// Model: Role
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::roles)]
#[diesel(primary_key(role_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Role {
    pub role_id: Uuid,
    pub type_: RoleType,
    pub name: String,
    pub description: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

// ============================================================================
// Model: Sessions
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::sessions)]
#[diesel(primary_key(session_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Sessions {
    pub session_id: Uuid,
    pub user_id: Uuid,
    pub identity_id: Uuid,
    pub refresh_token_hash: String,
    pub refresh_token_family: Uuid,
    pub user_agent: Option<String>,
    pub ip_address: Option<String>,
    pub device_type: Option<String>,
    pub refresh_token_expires_at: DateTime<Utc>,
    pub revoked_at: Option<DateTime<Utc>>,
    pub revoked_reason: Option<RevocationReason>,
    pub last_used_at: Option<DateTime<Utc>>,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
}

// ============================================================================
// Model: UserIdentity
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::user_identities)]
#[diesel(primary_key(identity_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct UserIdentity {
    pub identity_id: Uuid,
    pub user_id: Uuid,
    pub provider: IdentityProvider,
    pub provider_user_id: Option<String>,
    pub email: String,
    pub password_hash: Option<String>,
    pub password_changed_at: Option<DateTime<Utc>>,
    pub email_verified: Option<bool>,
    pub oauth_access_token: Option<String>,
    pub oauth_refresh_token: Option<String>,
    pub oauth_token_expires_at: Option<DateTime<Utc>>,
    pub is_primary: bool,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub last_login_at: Option<DateTime<Utc>>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub must_change_password: bool,
}

// ============================================================================
// Model: UserMfaTotp
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::user_mfa_totp)]
#[diesel(primary_key(user_mfa_totp_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct UserMfaTotp {
    pub user_mfa_totp_id: Uuid,
    pub user_id: Uuid,
    pub secret_encrypted: Vec<u8>,
    pub enabled: bool,
    pub enrolled_at: Option<DateTime<Utc>>,
    pub last_used_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

// ============================================================================
// Model: UserRecoveryCode
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::user_recovery_codes)]
#[diesel(primary_key(user_recovery_code_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct UserRecoveryCode {
    pub user_recovery_code_id: Uuid,
    pub user_id: Uuid,
    pub code_hash: String,
    pub used_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

// ============================================================================
// Model: UserRole
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::user_roles)]
#[diesel(primary_key(user_role_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct UserRole {
    pub user_role_id: Uuid,
    pub user_id: Uuid,
    pub role_id: Uuid,
    pub created_at: DateTime<Utc>,
    pub created_by: Option<Uuid>,
}

// ============================================================================
// Model: User
// ============================================================================
#[derive(
    Debug,
    Clone,
    Serialize,
    Deserialize,
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Identifiable,
    QueryableByName,
)]
#[diesel(table_name = crate::schema::users)]
#[diesel(primary_key(user_id))]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct User {
    pub user_id: Uuid,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub avatar_url: Option<String>,
    pub status: UserStatus,
    pub token_version: i32,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub mfa_required: bool,
    pub display_name: Option<String>,
}
