// @generated by scripts/gen_db_models_and_enums.sh
// DO NOT EDIT MANUALLY

use diesel_derive_enum::DbEnum;
use serde::{Deserialize, Serialize};

// ============================================================================
// Enum: EmailTemplateType
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize, DbEnum, PartialEq, utoipa::ToSchema)]
#[ExistingTypePath = "crate::schema::sql_types::EmailTemplateType"]
pub enum EmailTemplateType {
    EmailVerification,
    PasswordReset,
    PasswordChanged,
}

// ============================================================================
// Enum: IdentityProvider
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize, DbEnum, PartialEq)]
#[ExistingTypePath = "crate::schema::sql_types::IdentityProvider"]
pub enum IdentityProvider {
    EmailPassword,
    GoogleOauth,
    GithubOauth,
    MicrosoftOauth,
    AppleOauth,
    Saml,
    Ldap,
    Custom,
    TokenFederation,
}

// ============================================================================
// Enum: RevocationReason
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize, DbEnum, PartialEq)]
#[ExistingTypePath = "crate::schema::sql_types::RevocationReason"]
pub enum RevocationReason {
    UserLogout,
    PasswordChange,
    TokenCompromised,
    AccountSuspended,
    ManualRevocation,
    SuspiciousActivity,
    TokenRotation,
    Expired,
}

// ============================================================================
// Enum: RoleType
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize, DbEnum, PartialEq)]
#[ExistingTypePath = "crate::schema::sql_types::RoleType"]
pub enum RoleType {
    User,
    Admin,
    Support,
}

// ============================================================================
// Enum: UserStatus
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize, DbEnum, PartialEq, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
#[ExistingTypePath = "crate::schema::sql_types::UserStatus"]
pub enum UserStatus {
    Active,
    Inactive,
    Suspended,
    PendingVerification,
}
