// @generated by scripts/gen_db_models.sh
// DO NOT EDIT MANUALLY

use std::fmt;
use crate::schema_enums::*;

impl EmailTemplateType {
    pub fn as_str(&self) -> &'static str {
        match self {
            EmailTemplateType::EmailVerification => "email_verification",
            EmailTemplateType::PasswordReset => "password_reset",
            EmailTemplateType::PasswordChanged => "password_changed",
        }
    }
}

impl fmt::Display for EmailTemplateType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl IdentityProvider {
    pub fn as_str(&self) -> &'static str {
        match self {
            IdentityProvider::EmailPassword => "email_password",
            IdentityProvider::GoogleOauth => "google_oauth",
            IdentityProvider::GithubOauth => "github_oauth",
            IdentityProvider::MicrosoftOauth => "microsoft_oauth",
            IdentityProvider::AppleOauth => "apple_oauth",
            IdentityProvider::Saml => "saml",
            IdentityProvider::Ldap => "ldap",
            IdentityProvider::Custom => "custom",
        }
    }
}

impl fmt::Display for IdentityProvider {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl RevocationReason {
    pub fn as_str(&self) -> &'static str {
        match self {
            RevocationReason::UserLogout => "user_logout",
            RevocationReason::PasswordChange => "password_change",
            RevocationReason::TokenCompromised => "token_compromised",
            RevocationReason::AccountSuspended => "account_suspended",
            RevocationReason::ManualRevocation => "manual_revocation",
            RevocationReason::SuspiciousActivity => "suspicious_activity",
            RevocationReason::TokenRotation => "token_rotation",
            RevocationReason::Expired => "expired",
        }
    }
}

impl fmt::Display for RevocationReason {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl RoleType {
    pub fn as_str(&self) -> &'static str {
        match self {
            RoleType::User => "user",
            RoleType::Admin => "admin",
            RoleType::Support => "support",
        }
    }
}

impl fmt::Display for RoleType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl UserStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            UserStatus::Active => "active",
            UserStatus::Inactive => "inactive",
            UserStatus::Suspended => "suspended",
            UserStatus::PendingVerification => "pending_verification",
        }
    }
}

impl fmt::Display for UserStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

