#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# CONFIG
# ============================================================

DATABASE_URL="${DATABASE_URL:-postgresql://postgres:password@0.0.0.0:5432/sentinel_auth}"
SCHEMA_FILE="src/schema.rs"
MODELS_OUT="src/schema_models.rs"
ENUMS_OUT="src/schema_enums.rs"
ENUM_IMPLS_OUT="src/schema_enums_impls.rs"

# Extra derives to add to specific enums beyond the default set.
# Key = Rust enum name (PascalCase); Value = comma-separated derive list.
declare -A ENUM_EXTRA_DERIVES=(
  ["UserStatus"]="utoipa::ToSchema"
  ["EmailTemplateType"]="utoipa::ToSchema"
)

echo "==> [gen] Starting generation"
echo "==> [gen] SCHEMA_FILE:  $SCHEMA_FILE"
echo "==> [gen] MODELS_OUT:   $MODELS_OUT"
echo "==> [gen] ENUMS_OUT:    $ENUMS_OUT"

# ---- sanity checks ----
if ! command -v diesel >/dev/null 2>&1; then
  echo "!! [gen] diesel CLI not found in PATH" >&2
  exit 1
fi

if ! command -v psql >/dev/null 2>&1; then
  echo "!! [gen] psql not found in PATH (needed to read enum labels from Postgres)" >&2
  exit 1
fi

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "!! [gen] DATABASE_URL is not set. psql needs it to fetch enums." >&2
  echo "   Example: export DATABASE_URL='postgres://user:pass@localhost:5432/dbname'" >&2
  exit 1
fi

# ---- 1) generate schema.rs ----
echo "==> [gen] Running: diesel print-schema > $SCHEMA_FILE"
diesel print-schema > "$SCHEMA_FILE"
echo "==> [gen] schema.rs generated ($(wc -l < "$SCHEMA_FILE") lines)"

# ---- 2) generate db_models.rs ----
echo "==> [gen] Generating db models..."
rm -f "$MODELS_OUT"
touch "$MODELS_OUT"

awk -v OUT_FILE="$MODELS_OUT" '
BEGIN {
  print "==> [awk-models] generator started" > "/dev/stderr"

  print "// @generated by scripts/gen_db_models_and_enums.sh" > OUT_FILE
  print "// DO NOT EDIT MANUALLY\n" >> OUT_FILE

  print "use diesel::prelude::*;" >> OUT_FILE
  print "use serde::{Deserialize, Serialize};" >> OUT_FILE
  print "use uuid::Uuid;" >> OUT_FILE
  print "use chrono::{DateTime, Utc};" >> OUT_FILE
  print "" >> OUT_FILE

  print "use crate::schema_enums::*;" >> OUT_FILE
  print "" >> OUT_FILE
}

function trim(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); return s }

function snake_to_pascal(s,    n, i, p, out) {
  n = split(s, p, "_"); out = ""
  for (i = 1; i <= n; i++) out = out toupper(substr(p[i],1,1)) substr(p[i],2)
  return out
}

function singularize(tbl) {
  if (tbl ~ /ies$/) return substr(tbl, 1, length(tbl)-3) "y"
  if (tbl ~ /s$/ && tbl !~ /(status|sessions)$/) return substr(tbl, 1, length(tbl)-1)
  return tbl
}

function map_type(t,    inner) {
  t = trim(t)

  if (match(t, /^Nullable<(.+)>$/, m)) {
    inner = map_type(m[1])
    return "Option<" inner ">"
  }

  if (t == "Uuid") return "Uuid"
  if (t == "Text" || t == "Varchar" || t == "Bpchar") return "String"
  if (t == "Bool") return "bool"
  if (t == "Int2") return "i16"
  if (t == "Int4") return "i32"
  if (t == "Int8") return "i64"
  if (t == "Float4") return "f32"
  if (t == "Float8") return "f64"
  if (t == "Timestamptz") return "DateTime<Utc>"
  if (t == "Inet") return "std::net::IpAddr"
  if (t == "Bytea") return "Vec<u8>"
  if (t == "Json" || t == "Jsonb") return "serde_json::Value"

  if (match(t, /^Array<(.+)>$/, m)) {
    inner = map_type(m[1])
    return "Vec<" inner ">"
  }

  # IMPORTANT:
  # schema.rs often already exposes your Rust enum name (e.g., UserStatus)
  # so we keep unknown types as-is.
  return t
}

/^[ \t]*diesel::table![ \t]*\{/ {
  in_table = 1
  saw_one_close = 0
  table_name = ""
  pk = ""
  cols_count = 0
  print "==> [awk-models] found diesel::table! block" > "/dev/stderr"
  next
}

in_table && table_name == "" {
  if (match($0, /^[ \t]*([a-zA-Z0-9_]+)[ \t]*\([ \t]*([a-zA-Z0-9_]+)[ \t]*\)[ \t]*\{/, m)) {
    table_name = m[1]
    pk = m[2]
    print "==> [awk-models] table:", table_name, "pk:", pk > "/dev/stderr"
  }
  next
}

in_table {
  if (match($0, /^[ \t]*([a-zA-Z0-9_]+)[ \t]*->[ \t]*([^,]+),/, m)) {
    cols_name[cols_count] = m[1]
    cols_ty[cols_count] = trim(m[2])
    cols_count++
    next
  }

  # closing braces are on separate lines in schema.rs
  if ($0 ~ /^[ \t]*\}[ \t]*$/) {
    if (saw_one_close == 0) { saw_one_close = 1; next }

    tbl2 = singularize(table_name)
    struct_name = snake_to_pascal(tbl2)

    print "==> [awk-models] emitting struct:", struct_name > "/dev/stderr"

    print "// ============================================================================" >> OUT_FILE
    print "// Model: " struct_name >> OUT_FILE
    print "// ============================================================================" >> OUT_FILE

    print "#[derive(" >> OUT_FILE
    print "    Debug," >> OUT_FILE
    print "    Clone," >> OUT_FILE
    print "    Serialize," >> OUT_FILE
    print "    Deserialize," >> OUT_FILE
    print "    Queryable," >> OUT_FILE
    print "    Selectable," >> OUT_FILE
    print "    Insertable," >> OUT_FILE
    print "    AsChangeset," >> OUT_FILE
    print "    Identifiable," >> OUT_FILE
    print "    QueryableByName," >> OUT_FILE
    print ")]" >> OUT_FILE

    print "#[diesel(table_name = crate::schema::" table_name ")]" >> OUT_FILE
    print "#[diesel(primary_key(" pk "))]" >> OUT_FILE
    print "#[diesel(check_for_backend(diesel::pg::Pg))]" >> OUT_FILE
    print "pub struct " struct_name " {" >> OUT_FILE

    for (i = 0; i < cols_count; i++) {
      rust_ty = map_type(cols_ty[i])
      print "    pub " cols_name[i] ": " rust_ty "," >> OUT_FILE
    }

    print "}\n" >> OUT_FILE

    in_table = 0
    saw_one_close = 0
    table_name = ""
    pk = ""
    cols_count = 0
    next
  }

  next
}

END {
  print "==> [awk-models] generator finished" > "/dev/stderr"
}
' "$SCHEMA_FILE"

echo "==> [gen] Models generated: $MODELS_OUT"
echo "==> [gen] (lines) $(wc -l < "$MODELS_OUT")"

# ---- 3) generate enums.generated.rs from Postgres ----
echo "==> [gen] Generating enums from Postgres (pg_enum)..."
mkdir -p "$(dirname "$ENUMS_OUT")"
rm -f "$ENUMS_OUT"
touch "$ENUMS_OUT"

# Query: enum type name + labels
# Output format: typname|enumlabel
ENUM_ROWS="$(psql "$DATABASE_URL" -Atc "
SELECT t.typname, e.enumlabel
FROM pg_type t
JOIN pg_enum e ON t.oid = e.enumtypid
JOIN pg_namespace n ON n.oid = t.typnamespace
WHERE n.nspname = 'public'
ORDER BY t.typname, e.enumsortorder;
")"

if [[ -z "$ENUM_ROWS" ]]; then
  echo "!! [gen] No enums found in public schema (pg_enum returned nothing)." >&2
  echo "   enums file will still be generated with header only." >&2
fi

# helper: snake_case -> PascalCase
snake_to_pascal() {
  local s="$1"
  local out=""
  IFS="_" read -ra parts <<< "$s"
  for p in "${parts[@]}"; do
    out+="${p^}"
  done
  echo "$out"
}

# helper: enum label -> Rust variant PascalCase
label_to_variant() {
  local l="$1"
  # handle common labels like "pending_verification"
  snake_to_pascal "$l"
}

{
  echo "// @generated by scripts/gen_db_models_and_enums.sh"
  echo "// DO NOT EDIT MANUALLY"
  echo
  echo "use serde::{Deserialize, Serialize};"
  echo "use diesel_derive_enum::DbEnum;"
  echo
} >> "$ENUMS_OUT"

current_typ=""
declare -a variants=()

flush_enum() {
  local typ="$1"
  shift
  local -a vars=( "$@" )
  if [[ -z "$typ" ]]; then return; fi

  local rust_name
  rust_name="$(snake_to_pascal "$typ")"
  echo "==> [gen] emitting enum: $rust_name (pg type: $typ) with ${#vars[@]} variants"

  local extra_derives="${ENUM_EXTRA_DERIVES[$rust_name]:-}"
  local derive_line="Debug, Clone, Serialize, Deserialize, DbEnum, PartialEq"
  if [[ -n "$extra_derives" ]]; then
    derive_line="$derive_line, $extra_derives"
  fi

  {
    echo "// ============================================================================"
    echo "// Enum: $rust_name"
    echo "// ============================================================================"
    echo
    echo "#[derive($derive_line)]"
    echo "#[ExistingTypePath = \"crate::schema::sql_types::${rust_name}\"]"
    echo "pub enum ${rust_name} {"
    for v in "${vars[@]}"; do
      echo "    ${v},"
    done
    echo "}"
    echo
  } >> "$ENUMS_OUT"
}

# Build enums by grouping rows
while IFS='|' read -r typ label; do
  if [[ -z "$typ" ]]; then
    continue
  fi

  if [[ "$current_typ" != "$typ" ]]; then
    # flush previous
    flush_enum "$current_typ" "${variants[@]}"
    current_typ="$typ"
    variants=()
  fi

  variants+=( "$(label_to_variant "$label")" )
done <<< "$ENUM_ROWS"

# flush last
flush_enum "$current_typ" "${variants[@]}"

echo "==> [gen] Enums generated: $ENUMS_OUT"
echo "==> [gen] (lines) $(wc -l < "$ENUMS_OUT")"
echo "==> [gen] DONE"

echo "==> Generating schema_enums_impls.rs from $ENUMS_OUT..."
rm -f "$ENUM_IMPLS_OUT"
touch "$ENUM_IMPLS_OUT"

# -----------------------------
# Generate schema_enums_impls.rs
# (supports brace on next line)
# -----------------------------
awk -v OUT="$ENUM_IMPLS_OUT" -f /dev/stdin "$ENUMS_OUT" <<'AWK'
function trim(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); return s }

# Better handling for acronyms: ApiKey -> api_key (not a_p_i_key)
function pascal_to_snake_lower(s,    i, c, out, prev_lower_or_digit) {
  out = ""
  prev_lower_or_digit = 0
  for (i = 1; i <= length(s); i++) {
    c = substr(s, i, 1)
    if (c ~ /[A-Z]/) {
      if (i != 1 && prev_lower_or_digit) out = out "_"
      out = out tolower(c)
      prev_lower_or_digit = 0
    } else {
      out = out c
      if (c ~ /[a-z0-9]/) prev_lower_or_digit = 1
      else prev_lower_or_digit = 0
    }
  }
  return out
}

function emit_enum_impls() {
  if (variant_count <= 0 || enum_name == "") return

  print "impl " enum_name " {" >> OUT
  print "    pub fn as_str(&self) -> &'static str {" >> OUT
  print "        match self {" >> OUT
  for (i = 0; i < variant_count; i++) {
    v = variants[i]
    val = pascal_to_snake_lower(v)
    print "            " enum_name "::" v " => \"" val "\"," >> OUT
  }
  print "        }" >> OUT
  print "    }" >> OUT
  print "}" >> OUT
  print "" >> OUT

  print "impl fmt::Display for " enum_name " {" >> OUT
  print "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {" >> OUT
  print "        f.write_str(self.as_str())" >> OUT
  print "    }" >> OUT
  print "}" >> OUT
  print "" >> OUT
}

BEGIN {
  print "// @generated by scripts/gen_db_models.sh" > OUT
  print "// DO NOT EDIT MANUALLY" >> OUT
  print "" >> OUT
  print "use std::fmt;" >> OUT
  print "use crate::schema_enums::*;" >> OUT
  print "" >> OUT

  in_enum = 0
  waiting_for_brace = 0
  enum_name = ""
  variant_count = 0
}

# Detect `pub enum Name {` on same line OR `pub enum Name` (brace later)
/^[ \t]*pub[ \t]+enum[ \t]+[A-Za-z0-9_]+/ {
  enum_name = $0
  sub(/^[ \t]*pub[ \t]+enum[ \t]+/, "", enum_name)
  sub(/[ \t]*\{.*/, "", enum_name)
  enum_name = trim(enum_name)

  variant_count = 0
  delete variants

  if ($0 ~ /\{[ \t]*$/) {
    in_enum = 1
    waiting_for_brace = 0
  } else {
    waiting_for_brace = 1
    in_enum = 0
  }
  next
}

waiting_for_brace {
  if ($0 ~ /^[ \t]*\{[ \t]*$/) {
    in_enum = 1
    waiting_for_brace = 0
  }
  next
}

in_enum {
  if ($0 ~ /^[ \t]*\}[ \t]*$/) {
    emit_enum_impls()
    in_enum = 0
    enum_name = ""
    next
  }

  # Skip attributes, doc comments, and empty lines
  if ($0 ~ /^[ \t]*#/ || $0 ~ /^[ \t]*\/\/\// || $0 ~ /^[ \t]*$/) next

  line = trim($0)

  # Strip inline comments
  sub(/[ \t]*\/\/.*$/, "", line)

  # Variant line: `User,` or `User = "...",`
  sub(/,.*/, "", line)
  sub(/[ \t]*=.*/, "", line)
  line = trim(line)

  if (line ~ /^[A-Za-z_][A-Za-z0-9_]*$/) {
    variants[variant_count++] = line
  }
  next
}

END {
  if (in_enum) emit_enum_impls()
}
AWK
echo "==> Enum impls written to: $ENUM_IMPLS_OUT"
echo "==> [gen] (lines) $(wc -l < "$ENUM_IMPLS_OUT")"
echo "==> [gen] DONE"

